spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/Fintech
spring.datasource.username=postgres
spring.datasource.password=Swasthik@0318

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=FinTechAIAdvisorSecretKeyForJWTTokenGenerationAndValidationPurposes2024
jwt.expiration=86400000
